---
name: "Tagger - Move semantic tags!"
description: "Automatically move your semantic tags on release."
branding:
  icon: tag
  color: orange
inputs:
  tag:
    description: "The new tag. Other tags will be moved to this position."
    required: true
    default: ${{ github.ref }}
  prefix:
    description: "The prefix of the semantic tags."
    required: true
    default: ""
  token:
    description: "The github token."
    required: true
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Collect info
      id: info
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          bin=$DIR\\tagger.exe
        else
          bin="$DIR/tagger"
        fi
        echo "BIN=$bin" >> $GITHUB_OUTPUT
      shell: sh
      env:
        DIR: ${{ runner.temp }}
    - name: Download tagger (Linux, macOS)
      if: ${{ runner.os != 'Windows' }}
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          suffix=linux
        else
          suffix=mac
        fi
        wget https://github.com/fischerscode/tagger/releases/download/v0.1.0/tagger.${suffix} -O ${{ steps.info.outputs.BIN }}
        chmod +x ${{ steps.info.outputs.BIN }}
      shell: sh
    - name: Download tagger (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        Invoke-WebRequest -URI https://github.com/fischerscode/tagger/releases/download/v0.1.0/tagger.windows.exe -OutFile $Env:BIN
        echo "Saved to $Env:BIN"
      shell: pwsh
      env:
        BIN: ${{ steps.info.outputs.BIN }}
    - run: $BIN move -s -p '${{ inputs.prefix }}' ${INPUTS_TAG##*/}
      shell: bash
      env:
        INPUTS_TAG: ${{ inputs.tag }}
        BIN: ${{ steps.info.outputs.BIN }}
    - run: rm $BIN
      shell: sh
      env:
        BIN: ${{ steps.info.outputs.BIN }}
    - run: |
        repo=$(echo "${{ github.repositoryUrl }}" | sed "s,git://,https://${GITHUB_ACTOR}:${INPUT_TOKEN}@,")
        git push "$repo" --tags --force
      shell: sh
