---
name: "Tagger - Move semantic tags!"
description: "Automatically move your semantic tags on release."
branding:
  icon: tag
  color: orange
inputs:
  tag:
    description: "The new tag. Other tags will be moved to this position."
    required: true
    default: ${{ github.ref }}
  prefix:
    description: "The prefix of the semantic tags."
    required: true
    default: ""
  token:
    description: "The github token."
    required: true
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Download tagger
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          suffix=linux
        elif [ "${{ runner.os }}" = "macOS" ]; then
          suffix=mac
        else
          suffix=windows.exe
        fi
        wget https://github.com/fischerscode/tagger/releases/download/v0.1.0/tagger.${suffix} -O ${{ github.action_path }}/tagger
        chmod +x ${{ github.action_path }}/tagger
      shell: sh
    - run: ${{ github.action_path }}/tagger move -s -p '${{ inputs.prefix }}' ${INPUTS_TAG##*/}
      shell: bash
      env:
        INPUTS_TAG: ${{ inputs.tag }}
    - run: rm ${{ github.action_path }}/tagger
      shell: sh
    - run: |
        repo=$(echo "${{ github.repositoryUrl }}" | sed "s,git://,https://${GITHUB_ACTOR}:${INPUT_TOKEN}@,")
        git push "$repo" --tags --force
      shell: sh
